/**
 *
 *Each new term in the Fibonacci sequence is generated by adding the previous 
 *two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

     By considering the terms in the Fibonacci sequence whose values do not 
     exceed four million, find the sum of the even-valued terms.
 */
package solutionProjectEuler;

/**
 * @author nitin
 * Time : Morning (8:10) of Aug 28
 */
public class Prob2 {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		int fib1 = 1,fib2=2,next,sum;
		sum = fib2;//because the second terms itself is an even number
		
		next = generateFibonacci(fib1,fib2);
		
		while (next <= 4000000){//terms less than 4Million
			fib1=fib2;
			fib2=next;
			next = generateFibonacci(fib1,fib2);
			//Summing the even values terms
			if(next%2==0){
				sum = sum+next;
			}
			
			}
		System.out.println(sum);
				
		}
	
	
	public static int generateFibonacci(int fib1,int fib2){
		int next = fib1+fib2;
		return next;
	}
}

